---
author:
  - name: 'nelJapäevalised'
institute: Tallinn University
date: 2023-03-27
title: "Ruum4"

bibliography: references.bib
csl: ../../apa-numeric-superscript-brackets.csl
link-citations: yes

output-file: presentation_mid-term_katriin.html
format:
  revealjs:
    self-contained: true
    theme: [../olis.scss]
    slide-number: true
    logo: ../logos.png
multiplex:
  url: 'http://manual-for-rstudio.tennis24.ee:1948/'
  secret: "16759825730498538629"
  socketId: "f3edf0ff0d09982e"

---

## ELU-orJenteerumismäng

## TOPICS

## 

    Group members:
    Supervisor(s)/Mentor(s)
    Partner(s)


## BACKGROUND AND DESCRIPTION OF THE PROJECT

Teach the goals of sustainable development through study tracks
Pay more attention to SDG
World devastating situation
Trails availability
Increasing physical activity
Out of the box thinking

## IMPLEMENTATION OF ACTIVITIES

Different phases and tasks.
Assignments are entered into MathCityMap.
Rules we had to follow and the points that had to be observed.
The final result of the project -tracks where tasks include mathematics, various sustainable development goals, outdoor object and a studyfield.


## STAKEHOLDERS OF THE PROJECT
Trails can be used by all people who are willing and interested.
Teachers or youth workers offering non-formal learning opportunity.

## BASIS OF RESEARCH

Research papers and various scientific articles in ETERA.
Reliable sources, have used it before.


## INTERDISCIPLINARITY

By including the knowledge of different studyfields I can approach the solution of the problem from different perspectives.
Different web pages during the project.
RStudio program and through it we have also learned the R markdown language.

## TIMEFRAME OF THE PROJECT

Over two semesters
At the beginning of the first semester - focused on going through the tracks previously created by other people.
In the middle of the semester - creating our own track assignments.
By the beginning of the second semester - mainly working on correction and improvement.
Currently working on getting our first track ready and having it tested.

## OpenProject

![The main tool for managing the project is OpenProject as it also makes it possible to use Gantt charts.[@openproject].](../openproject-2023-03-26 21-16-40.png)

## PROJECT (GROUP) MID-TERM RESULTS
Six assignments that currently have a quality level of 1.
In the future, it is necessary to improve the tasks sufficiently so that they reach the required quality level. When the track is ready for testing, it is necessary to find suitable testers.

## FEEDBACK
Feedback meetings took place very rarely at the beginning, once or twice a week in the middle of the project, and at the moment as there is time and need.
Discussed the next meetings, agreed on suitable times to complete the tracks and worked on the tasks.

## Open Science Framework

![As the main door to our project both internally and externally has been serving Open Science Framework[@_2022_ruum4].](../osf-2023-03-26-05-33-00.png)

## THANK YOU FOR LISTENING

[Ruum4](/)

## External references

```{=tex}
\hyphenpenalty=10000
\fontspec{Symbola}

```